### PR TITLE
update steering committee permissions

### PR DESCRIPTION
**Pull request by knaaptime**
first draft of committee permissions

### CODE REVIEW

**Review by jGaboardi — APPROVED** [review]
Great wording.

**Review by sjsrey — APPROVED** [review]
Well put

**Review by ljwolf — APPROVED** [review]
This looks great!

**Review by martinfleis — APPROVED** [review]
Let's just keep in mind that we should first try to work together with maintainers of individual sub-packages before using this privilege.

**Comment by martinfleis** [comment]
I suppose that we should have a formal vote on this?

**Review by jGaboardi — APPROVED** [review]

**Comment by knaaptime** [comment]
shoulda done it today. Lets add a poll if you know how?

**Comment by jGaboardi** [comment]
Poll is here --> https://github.com/orgs/pysal/discussions/1295

**Comment by jGaboardi** [comment]
@sjsrey, @knaaptime, @martinfleis, @ljwolf  – Do we think a 1-week deadline is sufficient here since we all have already approved?

**Comment by jGaboardi** [comment]
One week deadline passed more than 6 months ago and I forgot to merge. Doing that now. We can revert if needed.

cc @sjsrey @knaaptime @martinfleis

**Pull request merged**
